openapi: 3.0.1

servers:
  - url: /api/v1

info:
  description: 'module: Destination'
  version: '1.0.0'
  title: 'Traveather'

tags:
  - name: Destination
    description: Destinations management

paths:
  /destination/list:
    get:
      operationId: retrieveDestinationsList
      summary: Retrieve destinations list
      description: It will return all destinations assigned to sign in user
      tags:
        - Destination
      responses:
        200:
          description: Destinations list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
              example:
                  id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                  name: 'destination_name'
                  createdAt:
                  createdBy:
                  modifiedAt:
                  archived:
                  description:
                  waypoint:
                    - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                      name: 'waypoint_name'
                      description: 'description_waypoint'
                      latitude: '54.372158'
                      longitude: '18.638306'
                      country: 'Poland'
                      region: 'Pomeranian'
                      city: 'Gdansk'
                      street: 'Grunwaldzka'
                      info: 'this is info'
                      items:
                        - id:
                          name: 'name'
                          description: 'description'

  /destination/{id}:
    get:
      operationId: retrieveDestination
      summary: Retrieve destination
      description: It will return specified destination by id.
      tags:
        - Destination
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
      responses:
        200:
          description: Destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
              example:
                id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                name: 'destination_name'
                createdAt:
                createdBy:
                modifiedAt:
                archived:
                description:
                waypoint:
                  - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                    name: 'waypoint_name'
                    description: 'description_waypoint'
                    latitude: '54.372158'
                    longitude: '18.638306'
                    country: 'Poland'
                    region: 'Pomeranian'
                    city: 'Gdansk'
                    street: 'Grunwaldzka'
                    info: 'this is info'
                    items:
                      - id:
                        name: 'name'
                        description: 'description'

    put:
      operationId: updateOrCreateDestination
      summary: Update or create destination
      description: Destination will be updated in case when id exists, otherwise it will create new one.
      tags:
        - Destination
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
            example:
              id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
              name: 'destination_name'
              createdAt:
              createdBy:
              modifiedAt:
              archived:
              description:
              waypoint:
                - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                  name: 'waypoint_name'
                  description: 'description_waypoint'
                  latitude: '54.372158'
                  longitude: '18.638306'
                  country: 'Poland'
                  region: 'Pomeranian'
                  city: 'Gdansk'
                  street: 'Grunwaldzka'
                  info: 'this is info'
                  items:
                    - id:
                      name: 'name'
                      description: 'description'
      responses:
        200:
          description: Succesfully updated or created destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'

  /destination:
    post:
      operationId: createDestination
      summary: Create Destination
      description: It will create destination if some validation requirements is correct.
      tags:
        - Destination
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
            example:
              id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
              name: 'destination_name'
              createdAt:
              createdBy:
              modifiedAt:
              archived:
              description:
              waypoint:
                - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                  name: 'waypoint_name'
                  description: 'description_waypoint'
                  latitude: '54.372158'
                  longitude: '18.638306'
                  country: 'Poland'
                  region: 'Pomeranian'
                  city: 'Gdansk'
                  street: 'Grunwaldzka'
                  info: 'this is info'
                  items:
                    - id:
                      name: 'name'
                      description: 'description'
      responses:
        200:
          description: Successfully created destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'

components:
  schemas:
    Destination:
      type: object
      required:
        - name
        - waypoint
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 128
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
        archived:
          type: boolean
          default: false
        description:
          type: string
          maxLength: 1024
        waypoint:
          $ref: '#/components/schemas/Waypoint'

    Waypoint:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1024
        latitude:
          type: number
          maxLength: 16
        longitude:
          type: number
          maxLength: 16
        country:
          type: string
          maxLength: 128
        region:
          type: string
          maxLength: 128
        city:
          type: string
          maxLength: 128
        street:
          type: string
          maxLength: 128
        info:
          type: string
          maxLength: 1024
        items:
          $ref: '#/components/schemas/Item'

    Item:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1024

    DestinationList:
      allOf:
        - type: object
          required:
            - items
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Destination'
