openapi: 3.0.1

servers:
  - url: /api/v1

info:
  description: 'module: Journey'
  version: '1.0.0'
  title: 'Traveather'

tags:
  - name: Journey
    description: Journeys management

paths:
  /journey/list:
    get:
      operationId: retrieveJourneysList
      summary: Retrieve journeys list
      description: It will return all journey assigned to sign in user
      tags:
        - Journey
      responses:
        200:
          description: Journeys list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Journey'
              example:
                id: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
                name: 'Trip around the world'
                createdAt: '2022-10-22T23:00:01Z'
                createdBy: 'admintest'
                modifiedAt: '2022-10-22T23:00:02Z'
                modifiedBy: 'admintest'
                archived: 'false'
                description: 'This is first journey'
                destination:
                  - id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                    name: 'destination_name'
                    createdAt:
                    createdBy:
                    modifiedAt:
                    archived:
                    description:
                    waypoint:
                      - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                        name: 'waypoint_name'
                        description: 'description_waypoint'
                        latitude: '54.372158'
                        longitude: '18.638306'
                        country: 'Poland'
                        region: 'Pomeranian'
                        city: 'Gdansk'
                        street: 'Grunwaldzka'
                        info: 'this is info'
                        items:
                          - id:
                            name: 'name'
                            description: 'description'

  /journey/{id}:
    get:
      operationId: retrieveJourney
      summary: Retrieve journey
      description: It will return specified journey by id.
      tags:
        - Journey
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example:
            id: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
            name: 'Trip around the world'
            createdAt: '2022-10-22T23:00:01Z'
            createdBy: 'admintest'
            modifiedAt: '2022-10-22T23:00:02Z'
            modifiedBy: 'admintest'
            archived: 'false'
            description: 'This is first journey'
            destination:
              - id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                name: 'destination_name'
                createdAt:
                createdBy:
                modifiedAt:
                archived:
                description:
                waypoint:
                  - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                    name: 'waypoint_name'
                    description: 'description_waypoint'
                    latitude: '54.372158'
                    longitude: '18.638306'
                    country: 'Poland'
                    region: 'Pomeranian'
                    city: 'Gdansk'
                    street: 'Grunwaldzka'
                    info: 'this is info'
                    items:
                      - id:
                        name: 'name'
                        description: 'description'
      responses:
        200:
          description: Journey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'

    put:
      operationId: updateOrCreateJourney
      summary: Update or create journey
      description: Journey will be updated in case when id exists, otherwise it will create new journey.
      tags:
        - Journey
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Journey'
            example:
              id: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
              name: 'Trip around the world'
              createdAt: '2022-10-22T23:00:01Z'
              createdBy: 'admintest'
              modifiedAt: '2022-10-22T23:00:02Z'
              modifiedBy: 'admintest'
              archived: 'false'
              description: 'This is first journey'
              destination:
                - id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                  name: 'destination_name'
                  createdAt:
                  createdBy:
                  modifiedAt:
                  archived:
                  description:
                  waypoint:
                    - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                      name: 'waypoint_name'
                      description: 'description_waypoint'
                      latitude: '54.372158'
                      longitude: '18.638306'
                      country: 'Poland'
                      region: 'Pomeranian'
                      city: 'Gdansk'
                      street: 'Grunwaldzka'
                      info: 'this is info'
                      items:
                        - id:
                          name: 'name'
                          description: 'description'
      responses:
        200:
          description: Succesfully updated or created journey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'

  /journey:
    post:
      operationId: createJourney
      summary: Create Journey
      description: It will create journey if some validation requirements is correct.
      tags:
        - Journey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Journey'
            example:
              id: 'cce62038-ea9a-4440-9e22-a2c9eccd22d5'
              name: 'Trip around the world'
              createdAt: '2022-10-22T23:00:01Z'
              createdBy: 'admintest'
              modifiedAt: '2022-10-22T23:00:02Z'
              modifiedBy: 'admintest'
              archived: 'false'
              description: 'This is first journey'
              destination:
                - id: '3c5ec55f-3025-46e9-9001-6fbf86fbd515'
                  name: 'destination_name'
                  createdAt:
                  createdBy:
                  modifiedAt:
                  archived:
                  description:
                  waypoint:
                    - id: '0c324580-cb3c-4def-bf05-cd6ee6487207'
                      name: 'waypoint_name'
                      description: 'description_waypoint'
                      latitude: '54.372158'
                      longitude: '18.638306'
                      country: 'Poland'
                      region: 'Pomeranian'
                      city: 'Gdansk'
                      street: 'Grunwaldzka'
                      info: 'this is info'
                      items:
                        - id:
                          name: 'name'
                          description: 'description'
      responses:
        200:
          description: Successfully created journey
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Journey'

components:
  schemas:
    Journey:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 128
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
        modifiedBy:
          type: string
          readOnly: true
        archived:
          type: boolean
          default: false
        description:
          type: string
          maxLength: 1024
        destinations:
          type: array
          items:
            $ref: '#/components/schemas/Destination'

    JourneyList:
      allOf:
        - type: object
          required:
            - items
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Journey'

    Destination:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 64
        name:
          type: string
          maxLength: 128
        createdAt:
          type: string
          format: date-time
          readOnly: true
        createdBy:
          type: string
          readOnly: true
        modifiedAt:
          type: string
          format: date-time
          readOnly: true
        archived:
          type: boolean
          default: false
        description:
          type: string
          maxLength: 1024
        waypoint:
          type: array
          items:
            $ref: '#/components/schemas/Waypoint'

    Waypoint:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          maxLength: 64
        description:
          type: string
          maxLength: 1024
        latitude:
          type: number
          maxLength: 16
        longitude:
          type: number
          maxLength: 16
        country:
          type: string
          maxLength: 128
        region:
          type: string
          maxLength: 128
        city:
          type: string
          maxLength: 128
        street:
          type: string
          maxLength: 128
        info:
          type: string
          maxLength: 1024
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'

    Item:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 128
        description:
          type: string
          maxLength: 1024

